# Generated by Django 6.0.2 on 2026-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_seller_chat_message_chatparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено'),
        ),
    ]
