# Generated by Django 6.0.2 on 2026-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_message_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='Модель / артикул'),
        ),
    ]
