# Generated by Django 6.0.2 on 2026-02-26 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('shop', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'role': 'user'})


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_likes_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Обычный пользователь'), ('businessman', 'Бизнесмен / Продавец'), ('moderator', 'Модератор')], default='user', max_length=20, verbose_name='Роль')),
                ('company_name', models.CharField(blank=True, help_text='Только для бизнесменов', max_length=200, verbose_name='Название компании / магазина')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
