# Generated by Django 6.0.2 on 2026-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_create_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('pending', 'На подтверждении'), ('approved', 'Подтверждён')], default='approved', max_length=20, verbose_name='Статус'),
        ),
    ]
