# Generated by Django 6.0.2 on 2026-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_brand_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль (hash)')),
                ('code', models.CharField(max_length=10, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Ожидающая регистрация',
                'verbose_name_plural': 'Ожидающие регистрации',
            },
        ),
    ]
